"use client";
import {useEffect,useState} from "react";
import {site,services,reviews,defaultGallery} from "@/data/site";
type Photo={src:string;title:string};
const key="pod-przykrywka-gallery";
export default function Home(){const [gallery,setGallery]=useState<Photo[]>(defaultGallery.map(([src,title])=>({src,title})));const [lightbox,setLightbox]=useState<number|null>(null);const [owner,setOwner]=useState(false);const [logged,setLogged]=useState(false);const [pass,setPass]=useState("");
useEffect(()=>{try{const x=localStorage.getItem(key);if(x)setGallery(JSON.parse(x))}catch{}},[]);
function save(x:Photo[]){setGallery(x);localStorage.setItem(key,JSON.stringify(x))}
function login(){if(pass==="demo123"){setLogged(true);setPass("")}else alert("Tryb demo: hasło to demo123")}
function add(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>save([...gallery,{src:String(r.result),title:"Nowe zdjęcie"}]);r.readAsDataURL(f)}
return <main><header className="nav"><a className="logo" href="#">pod <i>przykrywką</i></a><nav><a href="#o-nas">O nas</a><a href="#menu">Menu</a><a href="#galeria">Galeria</a><a href="#kontakt">Kontakt</a></nav><a className="navCta" href={"tel:"+site.phone.replaceAll(" ","")}>Zadzwoń</a></header>
<section className="hero"><div className="heroCopy"><span className="eyebrow">WROCŁAW · WIĘZIENNA 18</span><h1>Roślinna kuchnia,<br/><em>która ma charakter.</em></h1><p>Domowe smaki, nieoczywiste połączenia i talerz, do którego chce się wracać. Bez zadęcia. Pod przykrywką.</p><div className="actions"><a className="button dark" href="#menu">Zobacz menu <span>↗</span></a><a className="textLink" href={site.maps} target="_blank">Wyznacz trasę ↗</a></div></div><div className="heroVisual"><div className="heroCard"><span>4,8</span><b>★ ★ ★ ★ ★</b><small>{site.reviews} opinii</small></div></div></section>
<section className="ticker"><span>WEGE</span><span>DOMOWO</span><span>LOKALNIE</span><span>BEZ SPINY</span><span>OD SERCA</span></section>
<section id="o-nas" className="intro"><div><span className="eyebrow">01 · O NAS</span><h2>Nie musisz wybierać między <em>roślinnym</em> a pysznym.</h2></div><div className="introText"><p>Pod przykrywką to miejsce dla tych, którzy lubią dobrze zjeść. Gotujemy po swojemu, czerpiąc z kuchni domowej i polskich smaków, ale zostawiając im trochę miejsca na zaskoczenie.</p><p>Wpadnij na szybki obiad, zostań na coś słodkiego albo zamów do domu. Najważniejsze, żeby było Ci dobrze.</p></div></section>
<section id="menu" className="menuSection"><div className="sectionHead"><div><span className="eyebrow">02 · CO PODAJEMY</span><h2>Znane smaki.<br/><em>Nowa przykrywka.</em></h2></div><span className="stamp">40–60 zł<br/><small>za osobę</small></span></div><div className="serviceGrid">{services.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p><i>↗</i></article>)}</div></section>
<section id="galeria" className="gallerySection"><div className="sectionHead"><div><span className="eyebrow">03 · ZAJRZYJ DO ŚRODKA</span><h2>Trochę <em>od kuchni.</em></h2></div><p>Galeria jest edytowalna z panelu właściciela. Zdjęcia możesz wymieniać bez ruszania kodu.</p></div><div className="gallery">{gallery.map((p,i)=><button className={"photo p"+i%4} key={i} onClick={()=>setLightbox(i)}><img src={p.src} alt={p.title}/><span>{p.title} ↗</span></button>)}</div></section>
<section className="reviews"><div className="reviewScore"><span className="eyebrow">04 · GŁOSY GOŚCI</span><strong>{site.rating}</strong><div>★★★★★</div><p>{site.reviews} opinii w Google</p></div><div className="reviewList">{reviews.map(([who,text])=><blockquote key={who}><div>★★★★★</div><p>„{text}”</p><cite>{who}</cite></blockquote>)}</div></section>
<section id="kontakt" className="contact"><div className="contactTop"><span className="eyebrow">05 · WPADAJ</span><h2>Do zobaczenia<br/><em>przy stole.</em></h2><a className="button light" href={site.maps} target="_blank">Wyznacz trasę <span>↗</span></a></div><div className="contactGrid"><div><small>ADRES</small><p>{site.address}</p></div><div><small>TELEFON</small><p><a href={"tel:"+site.phone.replaceAll(" ","")}>{site.phone}</a></p></div><div><small>GODZINY</small>{site.hours.map(([d,h])=><div className="hours" key={d}><span>{d}</span><b>{h}</b></div>)}</div><div className="map"><iframe title="Mapa do Pod przykrywką" src={site.mapEmbed} loading="lazy"/></div></div></section>
<footer><div className="footerBrand">pod <i>przykrywką</i></div><div>© {new Date().getFullYear()} Pod przykrywką · Wrocław</div><div><a href={site.facebook} target="_blank">Facebook ↗</a><button onClick={()=>setOwner(true)}>Panel właściciela</button></div></footer>
{lightbox!==null&&<div className="overlay" onClick={()=>setLightbox(null)}><button className="close">×</button><img src={gallery[lightbox].src} alt={gallery[lightbox].title}/><div className="lbNav"><button onClick={e=>{e.stopPropagation();setLightbox((lightbox-1+gallery.length)%gallery.length)}}>←</button><span>{lightbox+1} / {gallery.length}</span><button onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%gallery.length)}}>→</button></div></div>}
{owner&&<div className="ownerOverlay"><div className="ownerPanel"><button className="close" onClick={()=>setOwner(false)}>×</button><span className="eyebrow">PRIVATE AREA</span><h2>Panel właściciela</h2>{!logged?<><p>Demo panel galerii. Dane są zapisywane lokalnie w tej przeglądarce.</p><input type="password" placeholder="Hasło" value={pass} onChange={e=>setPass(e.target.value)}/><button className="button dark full" onClick={login}>Zaloguj</button><small>Demo: demo123</small></>:<><div className="upload"><label className="button dark">+ Dodaj zdjęcie<input type="file" accept="image/*" onChange={add}/></label><span>{gallery.length} zdjęć w galerii</span></div><div className="ownerGallery">{gallery.map((p,i)=><div key={i}><img src={p.src} alt=""/><button onClick={()=>save(gallery.filter((_,j)=>j!==i))}>Usuń</button></div>)}</div></>}</div></div>}</main>